version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=arthur
      - POSTGRES_PASSWORD=arthur
      - POSTGRES_DB=hotel_lac_blanc
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
